### ISSUE TITLE
send_failed() notification causes an AttributeError exception

### ISSUE THREAD

**Issue by rpersch** [P1sec/pysctp#10]
The error occurs when the following conditions apply:
- subscribing to SCTP_SEND_FAILED notifications
- attempting to send a message to a peer that has become unavailable, e.g. due to a crash

The offending code is in line 392 of sctp.py, in the **init** method of the send_failed class:

```
del values._info
```

which should read

```
del self._info
```

**Comment by p1-bmu** [comment]
patch applied
