### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by oscarnyl** [P1sec/pysctp#13]
Python 3 support has been added in the following branch, but not pulled. https://github.com/lilydjwg/pysctp

**Comment by turicas** [comment]
SCTP is available on Python3 for GNU/Linux systems by installing `libsctp1`, `libsctp-dev` and `lksctp-tools` and do not require any other Python library than [Python's socket](https://docs.python.org/3/library/socket.html). [Read more about it](https://github.com/turicas/learning-sockets/tree/master/sctp).

**Comment by grnmeira** [comment]
@turicas The alternative seems interesting, but would it be possible to have access to settings like "PPID", for example? The C API the Linux sockets provide allows you to set, for example, the SCTP_DEFAULT_SEND_PARAM. I had no success doing the same using the IPPROTO_SCTP socket on Python, I get "OSError: Invalid argument".

**Comment by p1-olm** [comment]
Python 3 SCTP support lacks higher-level interface from libsctp (bindx / connectx ..), though same result can be achieve through setsockopt(). Python 3 port is still useful, but we could think of a 100% Python 3 SCTP module.

**Comment by p1-bmu** [comment]
_sctp.c and other Python files has been adapted to support both Python2 and Python3.
