### ISSUE TITLE
sctp_recv read same packet continuously

### ISSUE THREAD

**Issue by vikramkarandikar** [P1sec/pysctp#15]
I have developed a client server program where multiple clients connect to server and exchange sctp packets.
clients are places in one Virtual machine (VirtualBox) and Server is in another virtual machine, and interface is configured as host-only interface.

Environment
# uname -a

Linux ucc1 3.10.27-1.el6.elrepo.x86_64 #1 SMP Thu Jan 16 15:56:52 EST 2014 x86_64 x86_64 x86_64 GNU/Linux
# rpm -q lksctp-tools

lksctp-tools-1.0.10-7.el6.x86_64

two strange problems i am facing
1. all of a sudden sctp_recv keeps receiving same package indefinitely.
2. Some packets sent earlier get sent again and again randomly.

Any comments much appreciated.

**Comment by p1-bmu** [comment]
Should have been solved from last commits
