### ISSUE TITLE
How to install pysctp on windows 7

### ISSUE THREAD

**Issue by ghost** [P1sec/pysctp#16]
Hi,

I am trying to install pysctp on windows 7. I have python 2.7.8 installed.
D:\userdata\rkommine\Desktop\pysctp-0.6>python --version
Python 2.7.8

When I download the pysctp-0.6.tar.gz & extracted it & run the following command:
D:\userdata\rkommine\Desktop\pysctp-0.6>python setup.py install
running install
running build
running build_py
creating build
creating build\lib.win32-2.7
copying sctp.py -> build\lib.win32-2.7
running build_ext
building '_sctp' extension
error: Unable to find vcvarsall.bat

Could you please help how to install this modules on windows?

Thanks in advance.

Regards,
Ramakrishna

**Comment by domi007** [comment]
Hi,

Just for reference: you can fix the issue you're having by going to your Python installation (C:\Python27 for example)\Libs\distutils and open up cygwinccompiler.py and remove all occurences of -mcygwin, but it still will not help. It will say something about not being able to include net/sctp.h, and you can't really fix that:
https://www.cygwin.com/ml/cygwin/2009-02/msg00010.html

regards,
Domi

**Comment by p1-bmu** [comment]
pysctp wraps the Linux kernel SCTP socket, but Windows has no SCTP implementation matching the Linux kernel API. For this reason, pysctp won't work on Windows.
