### ISSUE TITLE
Issue Ubuntu 14.04 kernel version 4.2.0-27-generic 

### ISSUE THREAD

**Issue by hanuma19** [P1sec/pysctp#22]
does pysctp support for following configuration?
Ubuntu 14.04
kernel version 4.2.0-27-generic 
python 3.4.3

when I run "sudo python setup.py install --dry-run"  I see following  errors

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

 when I run "sudo ./test_local_cnx.py"  I see following  errors

ImportError: /home/hanuma/pysctp/pysctp/_sctp.so: undefined symbol: _Py_FalseStruct

can some body help me ?

**Comment by p1-bmu** [comment]
You have to install the required dependency first: libsctp-dev, python-dev or python3-dev...
