### ISSUE TITLE
set_sndbuf doesn't work as expected

### ISSUE THREAD

**Issue by shokuie** [P1sec/pysctp#32]
I'm at the very first stage of setting up an sctp connection between my application and a third party system. I'm getting ABORT with Invalid mandatory parameter cause in response to my INIT. At the same time, i have a working system and when comparing the pcaps the only differences in INIT phase are, 

1. Advertised receiver window credit / a_rwnd (mine is 106496 and the working one is 8192)
2. ECN parameter (which is not present in working version)

I thought let's start from the simple one and set the a_rwnd which i believe should be the sndbuf, I tried setting it, like the following snippet code:

```
tcp = sctpsocket(socket.AF_INET, socket.SOCK_STREAM, None)
saddr = (server, tcpport)
 
print("TCP %r ----------------------------------------------" % (saddr, )) 

tcp.initparams.max_instreams = 17
tcp.initparams.num_ostreams = 17

tcp.events.clear()
tcp.events.data_io = 1
tcp.set_sndbuf(16384)

size = tcp.get_sndbuf()
print("Buffer size: %d" % size)
```

After getting the sndbuf, i can see its set to the same 16384 value (i believe based on comments it should be devised by 2) but anyhow the problem is in the pcap the value for a_rwnd is still 106496 and doesn't change.

So can anyone first help me understand if sndbuf would set the a_rwnd in the actual INIT or I'm completely wrong here, and if it is why after calling set_sndbuf the value in the INIT still showing the old value?

**Comment by p1-bmu** [comment]
I did not checked in details, but:
1) pysctp is just a wrapper around the Linux SCTP stack, which can be configured at /proc/sys/net/sctp/
2) the indication of ECN support may be an issue for hosts not supporting ECN

**Comment by p1-bmu** [comment]
1. Could you please provide the pcap that shows the issue ?
2. I am not sure the local size set for *sndbuf* is related to the *a_rwnd* parameter provided in the SCTP association initialization.
