### ISSUE TITLE
pypi version 0.7 is outdated

### ISSUE THREAD

**Issue by astibal** [P1sec/pysctp#35]
Hi there,
just want to ask if you plan to update pip3 people at some point. Version there is outdated and suffers with randomly "echo" already received traffic. New version from git is totally ok.

Thanks,
Ales

**Comment by p1-bmu** [comment]
Thanks for contacting,
We are aware of this situation, waiting for the package manager to update the package on pip.

**Comment by p1-bmu** [comment]
I just uploaded the pypi package to the last git version.

**Comment by astibal** [comment]
that's brilliant, thanks!
