### ISSUE TITLE
How to configure source port for client

### ISSUE THREAD

**Issue by naseemr** [P1sec/pysctp#38]
Hi,
Can someone give me an example on how to configure source port?
Thanks,

**Comment by p1-bmu** [comment]
`bindx()` is the call to bind the socket after you created it and before you connect it with `connectx()`:
```
import sctp, socket
sk = sctp.sctpsocket_tcp(socket.AF_INET)
# bind it locally
sk.bindx([(myip1, myport1), ])
# connect it to the remote server
sk.connectx([(dstip1, dstport1), ])
```
