### ISSUE TITLE
SCTP Server when receiving SCTP request from other subnet do not work?

### ISSUE THREAD

**Issue by jajalcoding** [P1sec/pysctp#39]
Hi,

When I am creating a sctp server, and then getting the request from other subnets, somehow it doesn't work.
If both sctp client and server are in the same subnet, there is no issue.
Is there some more parameters that I need to change ?

Thank you very much.

Rgds

**Comment by jajalcoding** [comment]
Hi, after I captured the pcap, it looks like that when I have 2 NICs, sctp will use automatically multihoming.
And the issue I suspect is because it is using my primary NIC, meanwhile I setup gateway, etc. is on my second NIC.
Is there a way to disable multihoming, or force sctp just to use one of the interface ?
Thanks

**Comment by p1-bmu** [comment]
Please provide some more information: Linux variant / kernel version, python version, pysctp version... Eventually add the pcap. And maybe have a look at `bindx()` and `connectx()` too.
