### ISSUE TITLE
CI/CD publishing to PyPi

### ISSUE THREAD

**Issue by domi007** [P1sec/pysctp#43]
Hi Benoit,

I have seen you already started with CI/CD publishing of pycrate wheel to pypi. Thank you very much for that! I was wondering if you would be open to do it for this project as well? It would be much more convenient to have the binary wheels on pypi instead of just the source code, so server installation could be simplified (no need to maintain local builds or install gcc and headers onto servers).
I would be happy to contribute a simplified CI/CD yaml file for this project based on what you have in pycrate (https://github.com/P1sec/pycrate/blob/master/.github/workflows/cicd.yml), but it would still need your token to Pypi set in this project, so first I wanted to know if you would be open to support this?
Simplified would mean: rip out everything there is for Windows and Mac (?) because AFAIR pysctp is Linux only, and adjust tests etc.

Thanks,
Domi

**Comment by domi007** [comment]
Let me know if there are any issues with the PR, or you decided internally in P1 against it. If you want to see the resulting wheels check the artifacts in my fork (scroll to the bottom):
https://github.com/domi007/pysctp/actions/runs/3157404746

**Comment by p1-ra** [comment]
Hi Domi,

Your PR has been integrated, kudos and thanks for it!
