### ISSUE TITLE
_sctp.h goes in the wrong place

### ISSUE THREAD

**Issue by jeffsilverm** [P1sec/pysctp#5]
The Makefile that builds the _sctp.o file puts the _sctp.h in /usr/local. This isn't a problem for building/installing pysctp, but it's the wrong place: it should go in /usr/local/include so that other software can find it.

**Comment by p1-olm** [comment]
Fixed here https://github.com/p1-olm/pysctp/commit/2443a64223b4324d4bb62d8ba181e20720456e02

**Comment by p1-bmu** [comment]
setup.py has been updated accordingly
